# Copyright (c) 2024, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template with an EC2 instance
Parameters:
  KeyPairName:
    Description: >-
      This is used to ssh to the node. If you don't have a key, please create
      one from AWS console and rerun the script
    Type: 'AWS::EC2::KeyPair::KeyName'
  WSO2InstanceType:
    Description: 'EC2 instance type of the WSO2 EI Node [t2.micro is the free tier]'
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.medium
      - t3.large
      - c3.xlarge
      - c4.2xlarge
      - c5.2xlarge
      - c7g.xlarge
      - c7g.2xlarge
      - c6a.xlarge
      - c6a.2xlarge
    ConstraintDescription: must be a valid EC2 instance type
  WUMUsername:
    Type: String
    Default: ''
    Description: Enter WUM user name
  WUMPassword:
    Type: String
    Default: ''
    NoEcho: true
    Description: >-
      Enter WUM user password to get the updated WSO2 products deployed. If not
      provided standard released pack will be deployed
  Product:
    Type: String
    Default: wso2am
    Description: Enter product name
  ProductVersion:
    Type: String
    Default: 4.7.0
    Description: Enter product version
  OperatingSystem:
    Type: String
    Default: Rocky
    Description: >-
      Enter target OS. This will be the username of the created EC2 instances as
      well.
  S3OutputBucketLocation:
    Type: String
    Default: ""
  JDK:
    Type: String
    Default: ADOPT_OPEN_JDK8
    Description: Enter target JDK version.
    AllowedValues:
      - ADOPT_OPEN_JDK8
      - CORRETTO_JDK8
      - CORRETTO_JDK11
      - CORRETTO_JDK17
      - ADOPT_OPEN_JDK11
      - ADOPT_OPEN_JDK17
      - ADOPT_OPEN_JDK21
      - TEMURIN_OPEN_JDK8
  MavenVersion:
    Type: String
    Default: '3.6.3'
    Description: Enter required Maven version.
  CustomUserData:
   Type: String
   Default: "echo"
   Description: Enter custom user data scripts here.
  AWSAccessKeyId:
    Type: String
  AWSAccessKeySecret:
    Type: String
  UniqueIdentifier:
    Type: String
    Default: ""
Mappings:
  OperatingSystemAMI:
    Ubuntu:
      img: ami-02a2048d0e4afcd10
    Rocky:
      img: ami-0bdb0ee5983bfb6aa
#Conditions
Conditions:
 IsWindows: !Equals [ !Ref OperatingSystem, "Windows" ]
 IsUnix: !Or [ !Equals [ !Ref OperatingSystem, "CentOS"], !Equals [ !Ref OperatingSystem, "Ubuntu" ], !Equals [ !Ref OperatingSystem, "RHEL8" ], !Equals [ !Ref OperatingSystem, "RHEL9" ], !Equals [ !Ref OperatingSystem, "SUSE" ], !Equals [ !Ref OperatingSystem, "Rocky" ]]

Resources:
  WSO2InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for IS EC2 compute instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8140
          ToPort: 8140
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9763
          ToPort: 9763
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9443
          ToPort: 9443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8243
          ToPort: 8243
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8086
          ToPort: 8086
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 10173
          ToPort: 10173
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: abbdb5e8-f28b-4bc6-8b63-da9595b59c4a
  WSO2UnixInstance:
    Type: 'AWS::EC2::Instance'
    Condition: 'IsUnix'
    CreationPolicy:
      ResourceSignal:
        Count: '1'
        Timeout: PT60M
    Properties:
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      ImageId: !FindInMap
        - OperatingSystemAMI
        - !Ref OperatingSystem
        - img
      InstanceType: t2.large
      KeyName: !Ref KeyPairName
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
      Monitoring: 'false'
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: '50'
            VolumeType: gp2
            DeleteOnTermination: 'true'
      UserData: !Base64
        'Fn::Sub': |
              #!/bin/bash

              exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
              # Echoes all commands before executing.
              set -o verbose
              set -o xtrace

              # Set file limits
              sysctl -w fs.file-max=2097152
              sysctl fs.file-nr
              ulimit -Hn
              ulimit -Sn

              if [[ ${OperatingSystem} == "Ubuntu" ]]; then
                  export DEBIAN_FRONTEND=noninteractive
                  apt-get update
                  sleep 120
                  dpkg --configure -a
                  apt install -y zip
                  apt install -y python-pip
                  apt install -y jq
              fi
              if [[ ${OperatingSystem} == "CentOS" ]] || [[ ${OperatingSystem} == "RHEL8" ]] || [[ ${OperatingSystem} == "RHEL9" ]] || [[ ${OperatingSystem} == "Rocky" ]]; then
                yum install -y epel-release zip unzip
                yum install -y jq
                dnf update -y
                dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
                yum -y install wget
                                
                export JAVA_HOME=/usr/lib/jvm/jdk-11.0.21_9/
                export PATH=$JAVA_HOME/bin:$PATH
                echo "JAVA_HOME is set to $JAVA_HOME" >> /var/log/user-data.log
                
                source ~/.bashrc
      
                yum -y update
                yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  
                yum -y install git
              fi
              if [[ ${OperatingSystem} == "RHEL9" ]] || [[ ${OperatingSystem} == "Rocky" ]]; then
                pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
              else
                pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
              fi
              mkdir -p /opt/testgrid/workspace
              #So, provided permissions to all the users. Need to fix!
              sudo chmod 777 -R /opt/testgrid
              cd /opt/testgrid/workspace

              source /etc/environment

              cat /dev/null > ~/.bash_history && history -c
              ${CustomUserData}

              WORKING_DIR=$(pwd)

              # write property file
              echo "JDK_TYPE=${JDK}" >> cfn-props.properties
              #add product pack name to cfn properties
              echo "REMOTE_PACK_NAME=wso2am-${ProductVersion}" >> cfn-props.properties
              /usr/local/bin/aws --version
              /usr/local/bin/aws configure set aws_access_key_id '${AWSAccessKeyId}'
              /usr/local/bin/aws configure set aws_secret_access_key '${AWSAccessKeySecret}'
              /usr/local/bin/aws configure set default.region us-east-1
              /usr/local/bin/aws s3 cp s3://wum-for-testgrid/uat-config.json $WORKING_DIR/uat-config.json
              echo "Downloading vanilla product wso2am-${ProductVersion} from AWS S3 completed successfully"
              /usr/local/bin/aws s3 cp s3://wum-for-testgrid/packs/wso2am-${ProductVersion}.zip $WORKING_DIR
              if [[ ${OperatingSystem} == "RHEL8" ]] || [[ ${OperatingSystem} == "RHEL9" ]] || [[ ${OperatingSystem} == "SUSE" ]] || [[ ${OperatingSystem} == "Rocky" ]]; then
                alternatives --set python /usr/bin/python2
              fi

              aws s3 cp s3://apim-ui-testing/ui-staging-wso2-update.sh /opt/testgrid/workspace/staging-wso2-update.sh
              chmod +x /opt/testgrid/workspace/staging-wso2-update.sh

              /opt/testgrid/workspace/staging-wso2-update.sh ${WUMUsername} ${WUMPassword} wso2am-${ProductVersion}
  
              aws s3 cp s3://apim-ui-testing/instance-shutdown /etc/init.d/instance-shutdown
              sed -i "s~replace_by_product~wso2am~g" /etc/init.d/instance-shutdown
              sed -i "s~replace_by_version~${ProductVersion}~g" /etc/init.d/instance-shutdown
              sed -i "s~replace_by_s3_bucket_location~${S3OutputBucketLocation}/wso2-product-instance~g" /etc/init.d/instance-shutdown
              chmod +x /etc/init.d/instance-shutdown

              cat <<EOF > /etc/systemd/system/instance-shutdown.service
              [Unit]
              Description=Instance Shutdown Service
              Before=shutdown.target reboot.target halt.target
              Requires=network-online.target network.target
              
              [Service]
              KillMode=none
              Type=oneshot
              ExecStart=/bin/true
              ExecStop=/etc/init.d/instance-shutdown
              RemainAfterExit=yes
              
              [Install]
              WantedBy=multi-user.target
              EOF
    
              # Reload systemd to recognize the new service
              systemctl daemon-reload
    
              # Enable the instance-shutdown service to run at startup
              systemctl enable instance-shutdown
    
              # Start the instance-shutdown service
              systemctl start instance-shutdown
              
              # PUBLIC_DNS=$(curl http://169.254.169.254/latest/meta-data/public-hostname)
              # sed -i "s/localhost/$PUBLIC_DNS/g" wso2am-${ProductVersion}/repository/conf/deployment.toml

              PRIVATE_IP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4)
              sed -i "s/localhost/$PRIVATE_IP/g" wso2am-${ProductVersion}/repository/conf/deployment.toml
              
              DEPLOYMENT_TOML="wso2am-${ProductVersion}/repository/conf/deployment.toml"
          
              # Add application sharing configuration
              echo "" >> "$DEPLOYMENT_TOML"
              echo "" >> "$DEPLOYMENT_TOML"
              echo "[apim.devportal]" >> "$DEPLOYMENT_TOML"
              echo "enable_application_sharing = true" >> "$DEPLOYMENT_TOML"
              echo 'application_sharing_type = "default"' >> "$DEPLOYMENT_TOML"

              wso2am-${ProductVersion}/bin/api-manager.sh start
              sleep 60
              pwd
              echo ${OperatingSystem}
              if [[ ${OperatingSystem} == "Ubuntu" ]]; then
                /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WSO2UnixInstance --region ${AWS::Region}
              fi
              if [[ ${OperatingSystem} == "CentOS" ]]; then
                /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WSO2UnixInstance --region ${AWS::Region}
              fi
              if [[ ${OperatingSystem} == "RHEL8" ]] || [[ ${OperatingSystem} == "RHEL9" ]] || [[ ${OperatingSystem} == "Rocky" ]]; then
                /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WSO2UnixInstance --region ${AWS::Region}
              fi
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - 'ui-intg-test__'
              - !Ref OperatingSystem
              - '__'
              - !Ref JDK
      SecurityGroups:
        - !Ref WSO2InstanceSecurityGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8f512cce-69ee-45de-87ab-5aedd2a93d50
      "AWS::CloudFormation::Init" : {
          "config" : {
              "packages" : {
                  "apt" : {
                    }
                },
               "sources" : {
                },
               "files" : {
               }
          }
       }
  WSO2WindowsInstance:
      Type: 'AWS::EC2::Instance'
      Condition: 'IsWindows'
      Properties:
        DisableApiTermination: 'false'
        InstanceInitiatedShutdownBehavior: stop
        ImageId: FindInMap
          - OperatingSystemAMI
          - !Ref OperatingSystem
          - img
        InstanceType: !Ref WSO2InstanceType
        KeyName: !Ref KeyPairName
        Monitoring: 'false'
        "BlockDeviceMappings" : [
           {
              "DeviceName" : "/dev/sda1",
              "Ebs" : { "VolumeSize" : "100" }
           },
        ]
        UserData:
          !Base64
          'Fn::Sub': |
            <powershell>
            [Environment]::SetEnvironmentVariable("JAVA_HOME", "$Env:${JDK}", "Machine")
            ${CustomUserData}
            </powershell>
            <persist>true</persist>
        Tags:
          - Key: Name
            Value: !Join
              - ''
              - - 'ui-intg-test__'
                - !Ref OperatingSystem
                - '__'
                - !Ref JDK
        SecurityGroups:
          - !Ref WSO2InstanceSecurityGroup
      Metadata:
        'AWS::CloudFormation::Designer':
          id: 8f512cce-69ee-45de-87ab-5aedd2a93d50
        "AWS::CloudFormation::Init" : {
            "config" : {
                "packages" : {
                    "apt" : {
                      }
                  },
                 "sources" : {
                  },
                 "files" : {
                 }
            }
         }
Outputs:
  WSO2MgtConsoleURL:
    Value: !If [IsUnix, !Sub 'https://${WSO2UnixInstance.PublicDnsName}:9443/carbon', !If [IsWindows, !Sub 'https://${WSO2WindowsInstance.PublicDnsName}:9443/carbon', !Ref 'AWS::NoValue']]
    Description: Access URL of the Management Console
  WSO2PublicIP:
    Value: !If [IsUnix, !Sub '${WSO2UnixInstance.PublicIp}', !If [IsWindows, !Sub '${WSO2WindowsInstance.PublicIp}', !Ref 'AWS::NoValue']]
    Description: Private IP of the WSO2 Product Instance
  WSO2InstanceName:
    Value: !If [IsUnix, !Sub 'https://${WSO2UnixInstance.PublicDnsName}', !If [IsWindows, !Sub 'https://${WSO2WindowsInstance.PublicDnsName}', !Ref 'AWS::NoValue']]
    Description: Instance DNS Name
  OperatingSystem:
    Value: !Ref OperatingSystem
  WSO2InstanceId:
    Value: !If [IsUnix, !Ref WSO2UnixInstance, !If [IsWindows, !Ref WSO2WindowsInstance, !Ref 'AWS::NoValue']]
  GatewayHttpsUrl:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt 
          - WSO2UnixInstance
          - PrivateIp
        - ':8243'
    Description: WSO2 Unix Instance HTTPS URL
Metadata:
  'AWS::CloudFormation::Designer':
    abbdb5e8-f28b-4bc6-8b63-da9595b59c4a:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    d0dcc88f-97f7-4d80-901a-f746d372a295:
      size:
        width: 60
        height: 60
      position:
        x: -80
        'y': 210
      z: 1
      embeds: []
    5352b4e9-46ed-4a23-8bdc-bafc3666cbbd:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 210
      z: 1
      embeds: []
      isassociatedwith:
        - d0dcc88f-97f7-4d80-901a-f746d372a295
    8f512cce-69ee-45de-87ab-5aedd2a93d50:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 210
      z: 1
      embeds: []
      isassociatedwith:
        - abbdb5e8-f28b-4bc6-8b63-da9595b59c4a
      dependson:
        - 5352b4e9-46ed-4a23-8bdc-bafc3666cbbd
